# Generated by Django 5.2.17 on 2026-09-28 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.CharField(choices=[('DEPOSIT', 'Security deposit / advance rent'), ('BOOKING', 'Booking deposit'), ('SERVICE', 'Listing or service package')], max_length=20)),
                ('reference', models.CharField(help_text='What this payment is for', max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20)),
                ('conversation_id', models.CharField(blank=True, editable=False, max_length=64)),
                ('transaction_id', models.CharField(blank=True, editable=False, max_length=64)),
                ('provider_response', models.JSONField(blank=True, default=dict, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
