# Generated by Django 5.2.17 on 2026-09-16 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0004_message_status'),
        ('properties', '0002_alter_property_property_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('current_address', models.CharField(blank=True, max_length=255)),
                ('employment_status', models.CharField(choices=[('EMPLOYED', 'Employed (full-time)'), ('PART_TIME', 'Employed (part-time)'), ('SELF_EMPLOYED', 'Self-employed'), ('STUDENT', 'Student'), ('UNEMPLOYED', 'Unemployed'), ('RETIRED', 'Retired')], default='EMPLOYED', max_length=20)),
                ('employer', models.CharField(blank=True, max_length=150)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, help_text='Gross monthly income in TZS', max_digits=12, null=True)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('rental_history', models.TextField(blank=True, help_text='Past addresses / landlords, or any recent rental history.')),
                ('reference_name', models.CharField(blank=True, max_length=150)),
                ('reference_phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, upload_to='application_documents/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20)),
                ('decision_note', models.TextField(blank=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rental application',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_questions', to='properties.property')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_verified', models.BooleanField(default=False)),
                ('income_verified', models.BooleanField(default=False)),
                ('references_checked', models.BooleanField(default=False)),
                ('employment_verified', models.BooleanField(default=False)),
                ('background_checked', models.BooleanField(default=False)),
                ('score', models.PositiveSmallIntegerField(default=0, help_text='0–100')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening', to='engagement.application')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='engagement.application')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='engagement.applicationquestion')),
            ],
            options={
                'unique_together': {('application', 'question')},
            },
        ),
    ]
