# Generated by Django 5.2.17 on 2026-09-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0005_application_applicationquestion_applicationscreening_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationquestion',
            name='property',
        ),
        migrations.RemoveField(
            model_name='application',
            name='document',
        ),
        migrations.RemoveField(
            model_name='application',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='application',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='application',
            name='monthly_income',
        ),
        migrations.RemoveField(
            model_name='application',
            name='move_in_date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='reference_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='reference_phone',
        ),
        migrations.RemoveField(
            model_name='application',
            name='rental_history',
        ),
        migrations.AddField(
            model_name='application',
            name='agreement_accepted',
            field=models.BooleanField(default=False, help_text='Applicant confirms they have read and agree to the tenancy rules.'),
        ),
        migrations.DeleteModel(
            name='ApplicationAnswer',
        ),
        migrations.DeleteModel(
            name='ApplicationQuestion',
        ),
    ]
