# Generated by Django 5.2.17 on 2026-09-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('HOUSE', 'House'), ('ROOM', 'Single Room'), ('STUDIO', 'Studio'), ('OFFICE', 'Office'), ('HOSTEL', 'Hostel'), ('BNB', 'Airbnb / Short Stay')], max_length=20),
        ),
    ]
