# Generated by Django 5.2.17 on 2026-09-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='tenancy_rules',
            field=models.TextField(blank=True, default="1. Security deposit: Two months' rent, payable before move-in.\n2. Rent due date: 1st of each month.\n3. Notice period: One month written notice required to vacate.\n4. No subletting without written approval.\n5. Tenant responsible for minor repairs.\n6. Owner responsible for major structural repairs.\n7. Maximum occupants as agreed at signing.\n8. Pets not allowed unless otherwise agreed.", help_text='Rules tenants agree to when applying (deposit, notice period, house rules, etc.)'),
        ),
    ]
